name: Provision EC2 and Deploy Next.js App

on:
  repository_dispatch:
    types: 
      - deploy

jobs:
  terraform-apply:
    name: Provision EC2 and Deploy Application
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Terraform Repository
      - name: Checkout Terraform Repository
        uses: actions/checkout@v3

      - name: Inject GitHub Runner Token into User Data
        id: inject-token
        run: |
          sed -i "s/{{GH_RUNNER_TOKEN}}/${{ secrets.GH_RUNNER_TOKEN }}/g" install.sh



      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      # Initialize Terraform
      - name: Terraform Init
        working-directory: terraform/
        run: terraform init

      # # Apply Terraform
      # - name: Terraform Apply
      #   working-directory: terraform/
      #   run: terraform apply -auto-approve
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


      - name: Checkout Front-End Repo
        uses: actions/checkout@
        with:
          repository: stellatech-ca/marketup 
          token: ${{secrets.GH_PAT}}
          

     
  